/**
 * COMPASSION OF JESUS GLOBAL MISSION, ILORIN - SERMONS DATASET
 * Powered by Fastly Global CDN (GitHub Releases) for Instant 0-Lag Streaming & Fast Downloads!
 */

const sermonsData = [
  {
    id: "sermon-1",
    title: "Moving Forward and Upward",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-07-18",
    formattedDate: "July 18, 2026",
    category: "Sunday Service",
    series: "Kingdom Elevation",
    scripture: "Exodus 14:15",
    duration: "48:20",
    description: "An inspiring message on pressing forward beyond limitations into God's planned elevation for your life and destiny.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Moving.Forward.and.Upward.by.Pastor.Godwin.Adunmo.mp3",
    featured: true
  },
  {
    id: "sermon-2",
    title: "Thanksgiving",
    speaker: "Pastor Dolapo",
    date: "2026-07-18",
    formattedDate: "July 18, 2026",
    category: "Sunday Service",
    series: "Heart of Gratitude",
    scripture: "Psalm 100:4",
    duration: "42:15",
    description: "Understanding the spiritual key of thanksgiving that unlocks continuous divine multiplication and presence.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Thanksgiving.By.Pastor.Dolapo.mp3",
    featured: false
  },
  {
    id: "sermon-3",
    title: "The Might One in Battle",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-06-28",
    formattedDate: "June 28, 2026",
    category: "Sunday Service",
    series: "Spiritual Warfare",
    scripture: "Psalm 24:8",
    duration: "54:30",
    description: "A profound sermon on relying on God as the invincible warrior who fights and secures victory in all life battles.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Might.One.in.Battle.By.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-4",
    title: "The Secret Place",
    speaker: "Pastor Dolapo",
    date: "2026-06-21",
    formattedDate: "June 21, 2026",
    category: "Sunday Service",
    series: "Intimacy with God",
    scripture: "Psalm 91:1",
    duration: "45:10",
    description: "Deep spiritual insights on cultivating private prayer, quiet devotion, and abiding under the shadow of the Almighty.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Secret.Place.by.Pastor.Dolapo.mp3",
    featured: false
  },
  {
    id: "sermon-5",
    title: "God Our Healer",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-06-20",
    formattedDate: "June 20, 2026",
    category: "Sunday Service",
    series: "Divine Healing",
    scripture: "Exodus 15:26",
    duration: "50:45",
    description: "Unpacking Jehovah Rapha as the eternal restorer of body, mind, soul, and spirit.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/God.our.Healer.By.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-6",
    title: "God Our Restorer",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-06-20",
    formattedDate: "June 20, 2026",
    category: "Sunday Service",
    series: "Divine Restoration",
    scripture: "Joel 2:25",
    duration: "52:00",
    description: "Prophetic revelation on God restoring lost years, wasted health, broken joy, and stolen spiritual blessings.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/God.our.Restorer.By.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-7",
    title: "Are We Still Brethren?",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-05-23",
    formattedDate: "May 23, 2026",
    category: "Sunday Service",
    series: "Christian Love & Unity",
    scripture: "1 John 3:14",
    duration: "1h 15m",
    description: "A heart-searching sermon on restoring true brotherly love, unity, and genuine fellowship within the body of Christ.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Are.we.still.Brethren.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-8",
    title: "Jesus The Key That Opens Every Door Through the Manifestation of the Holy Spirit",
    speaker: "Minister Gbenga Sogbesan",
    date: "2026-05-11",
    formattedDate: "May 11, 2026",
    category: "Sunday Service",
    series: "Holy Spirit & Miracles",
    scripture: "Revelation 3:7",
    duration: "58:30",
    description: "Understanding how Jesus, operating through the power of the Holy Spirit, opens doors that no man can shut.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Jesus.The.Key.That.Opens.Every.Door.Through.the.Manifestation.of.the.Holy.Spirit.By.Minister.Gbenga.Sogbesan.mp3",
    featured: false
  },
  {
    id: "sermon-9",
    title: "The Impact of Relationships in Life and Destiny",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-05-08",
    formattedDate: "May 8, 2026",
    category: "Sunday Service",
    series: "Kingdom Wisdom",
    scripture: "Proverbs 13:20",
    duration: "47:15",
    description: "Crucial guidance on choosing divine relationships, associations, and mentorship for fulfilling your destiny.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Impact.of.Relationships.in.Life.and.Destiny.by.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-10",
    title: "The Principle of Harvest",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-04-26",
    formattedDate: "April 26, 2026",
    category: "Sunday Service",
    series: "Sowing & Reaping",
    scripture: "Galatians 6:7",
    duration: "49:40",
    description: "Biblical laws of spiritual seedtime and harvest for experiencing financial, spiritual, and relational fruitfulness.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Principle.of.Harvest.By.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-11",
    title: "The Mystery of the Kingdom IV (The Mystery of Fatherhood)",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-04-19",
    formattedDate: "April 19, 2026",
    category: "Sunday Service",
    series: "Mysteries of the Kingdom",
    scripture: "Ephesians 3:14-15",
    duration: "53:10",
    description: "Understanding God as Father, spiritual fatherhood, and inheriting the covenant promises of God.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Mystery.of.the.Kingdom.IV.The.Mystery.of.Fatherhood.by.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-12",
    title: "The Mystery of the Kingdom IV (The Mystery of the Resurrection)",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-04-18",
    formattedDate: "April 18, 2026",
    category: "Sunday Service",
    series: "Mysteries of the Kingdom",
    scripture: "Romans 8:11",
    duration: "51:20",
    description: "Unveiling the quickening power of the resurrection spirit that resurrects dead dreams, health, and spiritual life.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Mystery.of.the.Kingdom.IV.The.Mystery.of.the.Resurrection.by.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-13",
    title: "The Mystery of the Kingdom V (Unveiling the Mystery of God's Kingdom Blessings)",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-04-18",
    formattedDate: "April 18, 2026",
    category: "Sunday Service",
    series: "Mysteries of the Kingdom",
    scripture: "Ephesians 1:3",
    duration: "56:00",
    description: "Deep study into the spiritual mechanisms of kingdom blessings and walking in divine abundance.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Mystery.of.the.Kingdom.V.Unveling.the.Mystery.of.God.s.Kingdom.Blessings.by.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-14",
    title: "The Mystery of the Kingdom III (The Mystery of the Crucifixion)",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-04-04",
    formattedDate: "April 4, 2026",
    category: "Sunday Service",
    series: "Mysteries of the Kingdom",
    scripture: "Galatians 2:20",
    duration: "48:50",
    description: "The power of the cross, dying to self, and walking in the unyielding victory of Christ's finished work.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Mystery.of.the.Kingdom.III.The.Mystery.of.the.Crucifixion.By.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-15",
    title: "The Mystery of the Kingdom II (The Mystery of Sonship)",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-03-29",
    formattedDate: "March 29, 2026",
    category: "Sunday Service",
    series: "Mysteries of the Kingdom",
    scripture: "Romans 8:14",
    duration: "50:15",
    description: "Shifting from the mindset of servants to walking in the rights, inheritance, and authority of sons of God.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Mystery.of.the.Kingdom.II.The.Mystery.Sonship.By.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-16",
    title: "The Mystery of the Kingdom I (The Mystery of the Passover)",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Mysteries of the Kingdom",
    scripture: "Exodus 12:13",
    duration: "52:40",
    description: "Understanding the blood covenant of protection, deliverance, and immunity from evil.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Mystery.of.the.Kingdom.I.The.Mystery.of.the.Passover.By.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-17",
    title: "Accessing God's Secret for Success",
    speaker: "Pastor (Dr) Godwin Adunmo",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Kingdom Secrets",
    scripture: "Deuteronomy 29:29",
    duration: "46:30",
    description: "Discovering divine secrets and spiritual principles that guarantee outstanding success and distinction.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Accessing.God.s.secret.for.success.by.Pastor.Dr.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-18",
    title: "Breaking Forth New Ground",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Expansion & Growth",
    scripture: "Hosea 10:12",
    duration: "44:50",
    description: "Breaking up fallow ground, overcoming stagnation, and launching into new territories of impact.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Breaking.Forth.New.Ground_05-02-26_15-18-05-649.mp3",
    featured: false
  },
  {
    id: "sermon-19",
    title: "Discernment",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Spiritual Perception",
    scripture: "Hebrews 5:14",
    duration: "47:20",
    description: "Developing spiritual sensitivity to discern God's voice, avoid traps, and make spirit-led decisions.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Discernment.By.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-20",
    title: "Enforcing the New Covenant",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Covenant Rights",
    scripture: "Hebrews 8:6",
    duration: "49:10",
    description: "Enforcing your spiritual rights and privileges under the superior blood of Jesus.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Enforcing.the.New.Covenant.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-21",
    title: "Healing as a Blessing from God",
    speaker: "Pastor Dolapo",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Divine Healing",
    scripture: "3 John 1:2",
    duration: "41:30",
    description: "Understanding bodily health and divine healing as the rightful covenant bread of God's children.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Healing.as.a.blessing.from.God.Pastor.Dolapo.mp3",
    featured: false
  },
  {
    id: "sermon-22",
    title: "Miracle at Cana of Galilee",
    speaker: "Resident Pastor",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Gospel Miracles",
    scripture: "John 2:1-11",
    duration: "43:15",
    description: "When Jesus turns shame into honor, shortage into abundance, and reserves the best for last.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/miracle.at.Cana.of.Galilee.mp3",
    featured: false
  },
  {
    id: "sermon-23",
    title: "Overcoming the Storms of Life",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Faith Over Fear",
    scripture: "Mark 4:39",
    duration: "48:00",
    description: "Speaking peace to turbulent life circumstances through the authority of faith and the word of God.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Overcoming.the.storms.of.Life.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-24",
    title: "Profitable Living by Wisdom",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Wisdom for Living",
    scripture: "Ecclesiastes 10:10",
    duration: "45:40",
    description: "Applying divine wisdom for practical life choices, career growth, time management, and profitable living.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Profitable.living.by.wisdom.Pastor.Godwin.Adunmo.mp3",
    featured: false
  },
  {
    id: "sermon-25",
    title: "The Pursuit of Excellence",
    speaker: "Resident Pastor",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Kingdom Excellence",
    scripture: "Daniel 6:3",
    duration: "40:20",
    description: "Cultivating an excellent spirit in work, ministry, academics, and personal character for God's glory.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/The.Pursuit.of.Excellence.mp3",
    featured: false
  },
  {
    id: "sermon-26",
    title: "Triumphing in All Phases of Life",
    speaker: "Pastor Godwin Adunmo",
    date: "2026-03-28",
    formattedDate: "March 28, 2026",
    category: "Sunday Service",
    series: "Triumphant Living",
    scripture: "2 Corinthians 2:14",
    duration: "52:10",
    description: "Walking in perpetual victory in all seasons and transitions of life through Christ who always causes us to triumph.",
    driveUrl: "https://github.com/cooljaay/Compassion-church/releases/download/v1.0.0/Triumphing.in.all.phases.of.life.by.Pastor.Godwin.Adunmo.mp3",
    featured: false
  }
];

const churchDetails = {
  name: "Compassion of Jesus Global Mission",
  location: "Cucumber Guest House, Saw Mill, Ilorin, Kwara State",
  domain: "cjgmilorin.com",
  motto: "Go Ye Into All The World",
  welcomeMessage: "Listen online or download audio messages from Compassion of Jesus Global Mission, Ilorin.",
  serviceTimes: [
    { day: "Sunday Service", time: "8:00 AM" },
    { day: "Wednesday Bible Study", time: "5:00 PM" }
  ],
  address: "Cucumber Guest House, Saw Mill, Ilorin, Kwara State",
  phoneNumbers: ["+234 815 447 1308", "+234 803 292 0903"],
  contactEmail: "info@cjgmilorin.com"
};
